# coding: utf8
#
# This file is generated by att util tool.
# by 2012-01-06 14:18:50
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestLoginDc < Test::Unit::TestCase
  def setup
    @login_dc = keyword_proxy_for_class_name( DeviceDataCenter::LoginDc ).new
  end
  
  def test_login_dc
    # 登录DC
    assert_success do
      @login_dc.login_dc($common["dc_login_hash"])
    end
  end
  
end