# coding: utf8
# 
# This file is generated by att util tool.
# by 2011-12-09 09:45:42
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestProcessOperation < Test::Unit::TestCase
  def setup
    @process_operation = DeviceBack::ProcessOperation.new
    @network_operation = DeviceBack::NetworkOperation.new
  end
  
  def test_find_and_kill_process
    # tcpdump抓包,非阻塞执行tcpdump命令
    assert_success do
      @network_operation.tcpdump_package({:devicename => $common["device_name"], :block => "否",\
            :options => "-i eth3 | grep 192.168.11", :tmpfile => "/root/tcpdump.txt"})
    end
    sleep 20
    # 查找进程ID
    tcpdump_process_id = @process_operation.find_process_id({:devicename => $common["device_name"], :process => "tcpdump"})[0]
    # 杀死进程
    assert_success do
      @process_operation.force_to_kill_process({:devicename => $common["device_name"],:processid => tcpdump_process_id})
    end
    # 查找进程ID
    assert_hope("进程不存在") do
      @process_operation.find_process_id({:devicename => $common["device_name"], :process => "tcpdump"})[0]
    end
  end
  
end