# coding: utf8
#
# This file is generated by att util tool.
# by 2012-10-22 16:28:26
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'
$stdouttype = "UTF-8"

class TestHttpQuest < Test::Unit::TestCase
  def setup
    #you can use $local_pc_network_access_http_quest to quote hash as argument.
    @o = keyword_proxy_for_class_name( LocalPc::NetworkAccess::HttpQuest ).new
  end
  
  def test_http_test
    url = ""
    10241.times{ url << "/"}
    assert_success do
      @o.http_request({:address =>"111.168.8.138",:port =>"80",:request=>url})
    end
  end
  
end