# coding: utf8
#
# This file is generated by att util tool.
# by 2011-12-10 09:20:51
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../') unless $LOADED
require 'keywords/unittests/setup'

class TestCommon < Test::Unit::TestCase
  def setup
    #you can use $common to quote hash as argument.
    @o = keyword_proxy_for_class_name( Common ).new
  end
  
  def test_set_current_device
    flunk "not implent yet,please write code here"
  end
  
  def test_wait
    flunk "not implent yet,please write code here"
  end
  
end