# coding: utf-8
#
# This file is generated by att util tool.
# by 2012-12-19 10:18:25
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

class TestTamper < Test::Unit::TestCase
  def setup
    @common = Common.new
    @tamper_rule = keyword_proxy_for_class_name( DeviceConsole::ServerProtection::Tamper ).new
    assert_success do
    @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
  end
  
  def test_enable_disable_tamper
#    assert_success do
#      @tamper_rule.enable_disable_tamper({})
#    end
#     assert_success do
#      @tamper_rule.enable_disable_tamper({:enable_type => "禁用"})
#    end
  end

  def test_add_tamper_policy
    test_hashs = []
    test_hashs << {:name => "全部默认"}
#    test_hashs << {:name => "网站服务器",:url => "http://2.sinfor2.com",:protect_server => "2.sinfor2.com@_@2.2.2.2@;@abc.sinfor2.com@_@200.200.91.254@;@test.sinfor2.com@_@100.100.91.251"}
#    test_hashs << {:name => "篡改检测方式",:url => "http://3.sinfor3.com",:protect_server =>"3.sinfor3.com@_@6.6.6.6",:guard_method => "模糊中"}
#    test_hashs << {:name => "通知管理员",:url => "http://4.sinfor4.com",:protect_server =>"4.sinfor4.com@_@6.6.7.6",:is_alarm => "是", :alarm_email => "just_mail@system.mail",:alarm_sms =>""}
#    test_hashs << {:name => "是否阻止用户访问",:url => "http://4.sinfor5.com",:protect_server =>"4.sinfor5.com@_@6.7.7.6",:is_deter_visit_action => "是",:deter_visit_action => "重定向", :redirect_url => "http://127.0.0.1"}
    test_hashs.each { |test_hash|
      assert_success do
        @tamper_rule.add_tamper_policy(test_hash)
      end
    }
  end

    def test_edit_tamper_policy
    test_hashs = []
#    test_hashs << {:name => "全部默认"}
#    test_hashs << {:name => "网站服务器",:url => "http://2.sinfor2.com",:protect_server => "2.sinfor2.com@_@2.3.2.2@;@abc.sinfor2.com@_@200.201.91.254@;@test.sinfor2.com@_@100.100.91.231"}
#    test_hashs << {:name => "篡改检测方式",:url => "http://3.sinfor3.com",:protect_server =>"3.sinfor3.com@_@6.6.6.6",:guard_method => "模糊低",:is_check_hotlink=>"否"}
#    test_hashs << {:name => "通知管理员",:url => "http://4.sinfor4.com",:protect_server =>"4.sinfor4.com@_@6.6.7.6",:is_alarm => "否", :alarm_email => "just_mail1@system.mail",:alarm_sms =>""}
#    test_hashs << {:name => "是否阻止用户访问",:url => "http://4.sinfor5.com",:protect_server =>"4.sinfor5.com@_@6.7.7.6",:is_deter_visit_action => "是",:deter_visit_action => "提示页面", :redirect_url => "http://127.0.0.1"}
    test_hashs.each { |test_hash|
      assert_success do
        @tamper_rule.edit_tamper_policy(test_hash)
      end
    }
  end

    def test_del_tamper_policy
    test_hashs = []
    test_hashs << {:name => "全部默认"}
    test_hashs << {:name => "网站服务器@;@篡改检测方式@;@是否阻止用户访问"}
    test_hashs.each { |test_hash|
      assert_success do
        @tamper_rule.del_tamper_policy(test_hash)
      end
    }
  end
  
  
end