# coding: utf8
#
# This file is generated by att util tool.
# by 2011-12-08 15:58:38
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'


class TestVirusDefense < Test::Unit::TestCase
    def setup
    @common = Common.new
    @interface_zone = DeviceConsole::NetConfig::InterfaceZone.new
    @ip_group = DeviceConsole::ObjectDefinition::IpGroup.new
    @virus_defense = DeviceConsole::ContentSecurity::VirusDefense.new

    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end

  end
  def test_edit_virus_rule()
    assert_success do
      @interface_zone.add_zone(:name => "zone41", :forward_type => "三层区域", :interfaces => "",
        :enable_webui => "是", :enable_ssh => "是", :enable_snmp => "是", :manage_address => "全部")
    end
     # 新增区域
    assert_success do
      @interface_zone.add_zone(:name => "zone42", :forward_type => "三层区域", :interfaces => "",
        :enable_webui => "否", :enable_ssh => "否", :enable_snmp => "否", :manage_address => "全部")
    end
    # 新增IP组,正常
    assert_success do
      @ip_group.add_ip_group({:group_name => "ipgrp41", :description => "描述", :ip_addresses => "2.2.2.2&1.1.1.1-1.1.1.100"})
    end
    assert_success do
      @virus_defense.edit_virus_rule({:enable => "是", :source_zone => "zone41&zone42", :source_group_type => "IP组", :source_ip => "ipgrp41",\
            :source_user => "", :dest_zone => "zone41&zone42", :virus_http => "是",:virus_ftp => "否",\
            :virus_pop3 => "是",:virus_smtp => "是", :virus_filetype => "bat&com",\
            :enable_url => "是",:url_list =>"1.5.6.7&2.3.6.12",
            :operation => "是", :record_log => "是"})
    end
    assert_success do
      @virus_defense.edit_virus_rule({:enable => "否", :source_zone => "", :source_group_type => "IP组", :source_ip => "",\
            :source_user => "", :dest_zone => "", :virus_http => "是",:virus_ftp => "否",\
            :virus_pop3 => "是",:virus_smtp => "是", :virus_filetype => "",\
            :enable_url => "是",:url_list =>"",
            :operation => "是", :record_log => "是"})
    end
     # 删除所有的IP组
    assert_success do
      @ip_group.delete_ip_group({ :delete_type => "全部删除", :group_names => ""})
    end
    # 删除所有的区域
    assert_success do
      @interface_zone.delete_zone( {:delete_type => "全部删除", :names => ""})
    end
  end
end
