# coding: utf8
#
# This file is generated by att util tool.
# by 2012-01-09 20:12:43
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestUserOnLineManagement < Test::Unit::TestCase
  def setup
    @common = Common.new
    @user_online = keyword_proxy_for_class_name( DeviceConsole::RunState::UserOnLineManagement ).new

    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
  end
  
  def test_force_logoff_user
    # 注销在线用户
    assert_success do
      @user_online.force_logoff_user({:usernames => "user1", :fatherpath => "/AF", :ip => ""})
    end
    # 注销在线用户,指定正确的IP
    assert_success do
      @user_online.force_logoff_user({:usernames => "user1", :fatherpath => "/AF", :ip => "192.168.101.2"})
    end
    # 注销在线用户,指定错误的IP
    assert_success do
      @user_online.force_logoff_user({:usernames => "user1", :fatherpath => "/AF", :ip => "192.168.101.66"})
    end
    # 注销不在线的用户
    assert_hope("用户不存在") do
      @user_online.force_logoff_user({:usernames => "user88", :fatherpath => "/AF", :ip => ""})
    end
  end
  
end