# coding: utf8
#
# This file is generated by att util tool.
# by 2011-12-14 14:44:58
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestLogin < Test::Unit::TestCase
  def setup
    @common = Common.new
    @login = keyword_proxy_for_class_name( DeviceConsole::Login ).new

  end
  
  def test_login
    # 正确的网关IP,用户名密码
    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
    # 登录控制台
    assert_success do
      @login.login({})
    end
    # 正确的网关IP,错误的用户名密码
    assert_success do
      @common.set_current_device( $common["login_hash2"] ) # 设置错误的用户名,密码
    end
    # 登录控制台
    assert_fail do
      @login.login({})
    end
    # 错误的网关IP
    assert_success do
      @common.set_current_device( $common["login_hash3"] ) # 设置错误的设备的IP
    end
    # 登录控制台
    assert_fail do
      @login.login({})
    end
  end
  
end