# coding: utf-8
#
# This file is generated by att util tool.
# by 2012-12-24 15:53:06
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

class TestVirtualLine < Test::Unit::TestCase
  def setup
    #you can use $device_console_flux_manager_virtual_line to quote hash as argument.
    @common = Common.new
    @o = keyword_proxy_for_class_name( DeviceConsole::FluxManager::VirtualLine ).new
    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
  end
  
  def test_add_vline
    test_hashs = []
#    test_hashs << {} # => 默认值添加
#    test_hashs << {:out_eth =>"eth3",:up =>"10240",:down => "10240"} # => 配置数据增加
    test_hashs.each { |test_hash|
      assert_success do
        @o.add_vline(test_hash)
      end
    }
  end
  
  def test_del_vline
    test_hashs = []
#    test_hashs << {} # => ....
#    test_hashs << {} # => 删除与线路号无关
    test_hashs.each { |test_hash|
      assert_success do
        @o.del_vline(test_hash)
      end
    }
  end
  
  def test_edit_vline
    test_hashs = []
#    test_hashs << {:line_num => 2,:out_eth =>"eth2",:up =>"130340",:down => "13340"} # => ....
#    test_hashs << {:line_num => 3,:out_eth =>"eth2",:up =>"180240",:down => "18240"} # => 修改规则
    test_hashs.each { |test_hash|
      assert_success do
        @o.edit_vline(test_hash)
      end
    }
  end
  
  def test_add_vline_rule
    test_hashs = []
#    test_hashs << {}
#    test_hashs << {:type => "tcp",:proto_num =>"6",:lan_ip =>"指定IP范围",:lan_ip_range =>"5.6.7.8",:lan_port =>"指定端口范围",:lan_port_range =>"88-99",
#      :wan_ip => "指定IP范围",:wan_ip_range => "2.2.2.2-2.2.2.3",:target_line => "3", :wan_port =>"指定端口范围",:wan_port_range =>"88-99"} # => ....
    test_hashs.each { |test_hash|
      assert_success do
        @o.add_vline_rule(test_hash)
      end
    }
  end
  
  def test_del_vline_rule
    test_hashs = []
#    test_hashs << {}
#    test_hashs << {:name => 2}
#    test_hashs << {:line_num => 2,:out_eth =>"eth2",:up =>"130340",:down => "13340"} # => ....
#    test_hashs << {:line_num => 3,:out_eth =>"eth2",:up =>"180240",:down => "18240"} # => 修改规则
    test_hashs.each { |test_hash|
      assert_success do
        @o.del_vline_rule(test_hash)
      end
    }
  end
  
  def test_edit_vline_rule
    test_hashs = []
    test_hashs << {}
    test_hashs << {:name =>"2",:type => "tcp",:proto_num =>"6",:lan_ip =>"指定IP范围",:lan_ip_range =>"5.6.7.8",:lan_port =>"指定端口范围",:lan_port_range =>"88-99",
      :wan_ip => "指定IP范围",:wan_ip_range => "2.2.2.2-2.2.2.3",:target_line => "3", :wan_port =>"指定端口范围",:wan_port_range =>"88-99"} # => ....
    test_hashs.each { |test_hash|
      assert_success do
        @o.edit_vline_rule(test_hash)
      end
    }
  end
  
end