# coding: utf8
#
# This file is generated by att util tool.
# by 2011-12-09 10:24:38
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestSystemConfiguration < Test::Unit::TestCase
  def setup
    @common = Common.new
    @system_config = DeviceConsole::System::SystemConfiguration.new

    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
  end

  def test_get_system_time
    date, time = @system_config.get_system_time({})
  end

  def test_set_system_time
    # 设置系统时间
    assert_success do
      @system_config.set_system_time({:date => "2010-01-02", :time => "13:20:05"})
    end
  end
  
end