# coding: utf8
#
# This file is generated by att util tool.
# by 2012-01-29 09:43:26
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestLogSetting < Test::Unit::TestCase
  def setup
    @common = Common.new
    @log_setting = keyword_proxy_for_class_name( DeviceConsole::System::LogSetting ).new

    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置当前设备的IP,用户名,密码
    end
  end
  
  def test_modify_inner_dc_setting
    assert_success do
      @log_setting.modify_inner_dc_setting({:enable_inner_dc => "是", :method => "天数", :days => "2", :percentage => "80", :enable_merge => "是"})
    end
    assert_success do
      @log_setting.modify_inner_dc_setting({:enable_inner_dc => "是", :method => "天数", :days => "15", :percentage => "80", :enable_merge => "是"})
    end
    assert_success do
      @log_setting.modify_inner_dc_setting({:enable_inner_dc => "是", :method => "磁盘空间", :days => "2", :percentage => "70", :enable_merge => "是"})
    end
    assert_success do
      @log_setting.modify_inner_dc_setting({:enable_inner_dc => "是", :method => "磁盘空间", :days => "2", :percentage => "80", :enable_merge => "是"})
    end
    assert_success do
      @log_setting.modify_inner_dc_setting({:enable_inner_dc => "否", :method => "天数", :days => "15", :percentage => "80", :enable_merge => "否"})
    end
    assert_success do
      @log_setting.modify_inner_dc_setting({:enable_inner_dc => "是", :method => "天数", :days => "1", :percentage => "80", :enable_merge => "是"})
    end
  end
  
end