# coding: utf8
#
# This file is generated by att util tool.
# by 2012-01-05 16:16:23
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

class TestRebootDevice < Test::Unit::TestCase
  def setup
    
    @o = keyword_proxy_for_class_name( DeviceConsole::SystemMantenance::RebootDevice ).new
  end
  
  def test_reboot_device
    
  end
  
  def test_reboot_service
    
  end
  
end