# coding: utf8
#
# This file is generated by att util tool.
# by 2012-08-24 17:44:44
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

class TestDlpIdentifyLib < Test::Unit::TestCase
  def setup
    @common = Common.new
    @test_obj = keyword_proxy_for_class_name( DeviceConsole::SecureDefenceObject::DlpIdentifyLib ).new
    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
    @hash_new_1 = { :name => "test_woolen_1", :suspic => "just_test_1", :hope => "成功"}
    @hash_new_2 = { :name => "test_woolen_2", :suspic => "just_test_2", :hope => "成功"}
    @hash_edit_1 = { :name => "test_woolen_2", :suspic => "just_test_2", :hope => "成功"}
    @hash_edit_2 = { :name => "test_woolen_2", :suspic => "just_test_2", :hope => "成功"}
    @hash_del_1 = { :delete_type => "部分删除", :names => "test_woolen_1", :hope => "成功"}
    @hash_del_all = { :delete_type => "全部删除", :names => "test_woolen_2", :hope => "成功"}
  end
  
  def test_new_userdefine_suspic
    puts("这里是 test_new_userdefine_suspic ... ===================@@Woolen Test@@====================")
    assert_success do
      @test_obj.new_userdefine_suspic(@hash_new_1)
    end
    assert_success do
      @test_obj.new_userdefine_suspic(@hash_new_2)
    end
  end
  
  def test_edit_userdefine_suspic
    puts("这里是 test_edit_userdefine_suspic ... ===================@@Woolen Test@@====================")
    assert_success do
      @test_obj.del_userdefine_suspic(@hash_del_all)
    end
    assert_success do
      @test_obj.new_userdefine_suspic(@hash_new_1)
    end
    assert_success do
      @test_obj.new_userdefine_suspic(@hash_new_2)
    end
    assert_success do
      @test_obj.edit_userdefine_suspic(@hash_edit_1)
    end
    assert_success do
      @test_obj.edit_userdefine_suspic(@hash_edit_2)
    end
  end
  
  def test_del_userdefine_suspic
    puts("这里是 test_del_userdefine_suspic ... ===================@@Woolen Test@@====================")
    assert_success do
      @test_obj.new_userdefine_suspic(@hash_new_1)
    end
    assert_success do
      @test_obj.new_userdefine_suspic(@hash_new_2)
    end
    assert_success do
      @test_obj.del_userdefine_suspic(@hash_del_1)
    end
    assert_success do
      @test_obj.del_userdefine_suspic(@hash_del_all)
    end
  end
  
  def teardown
    puts("这里是 test_del_userdefine_suspic ... ===================@@Woolen Test@@====================")
    assert_success do
      @test_obj.del_userdefine_suspic(@hash_del_all)
    end
  end
end