# coding: utf8
#
# This file is generated by att util tool.
# by 2012-08-25 09:37:21
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

class TestDlpIdentifyLibExcludeUrl < Test::Unit::TestCase
  def setup
    @common = Common.new
    @test_obj = keyword_proxy_for_class_name( DeviceConsole::SecureDefenceObject::DlpIdentifyLibExcludeUrl ).new
    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
    
    @hash_new_1 = { :exclude_url => "/a/b/c&/c/d/e", :hope => "成功"}
    @hash_new_2 = { :exclude_url => "/d/e/f&/h/i&/j/k", :hope => "成功"}
    @hash_edit_1 = { :name => "/a/b/c", :exclude_url => "/a/b/c/d", :hope => "成功"}
    @hash_edit_2 = { :name => "/d/e/f", :exclude_url => "/a/b/c/d/e&/h/h/h/h", :hope => "成功"}
    @hash_del_1 = { :delete_type => "部分删除", :names => "/a/b/c&/c/d/e", :hope => "成功"}
    @hash_del_all = { :delete_type => "全部删除", :names => "/a/b/c", :hope => "成功"}
    
  end
  
  def test_new_dlp_exclude_url
    puts("这里是 test_new_dlp_exclude_url ...测 新建......")
    assert_success do
      @test_obj.new_dlp_exclude_url(@hash_new_1)
    end
    assert_success do
      @test_obj.new_dlp_exclude_url(@hash_new_2)
    end
  end
  
  def test_edit_dlp_exclude_url
    puts("这里是 test_edit_dlp_exclude_url ...测编辑......")
    assert_success do
      @test_obj.new_dlp_exclude_url(@hash_new_1)
    end
    assert_success do
      @test_obj.new_dlp_exclude_url(@hash_new_2)
    end
    # => 前置添加好了再编辑
    assert_success do
      @test_obj.edit_dlp_exclude_url(@hash_edit_1)
    end
    assert_success do
      @test_obj.edit_dlp_exclude_url(@hash_edit_2)
    end
  end
  
  def test_del_dlp_exclude_url
    puts("这里是test_del_dlp_exclude_url...测试删除......")
    assert_success do
      @test_obj.new_dlp_exclude_url(@hash_new_1)
    end
    assert_success do
      @test_obj.del_dlp_exclude_url(@hash_del_1)
    end
  end
  
  
  def teardown
    puts("这里是teardown...收拾环境......")
    assert_success do
      @test_obj.del_dlp_exclude_url(@hash_del_all)
    end
  end
end