# coding: utf8
#
# This file is generated by att util tool.
# by 2011-12-07 17:20:51
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "GBK"

class TestVirtualCable < Test::Unit::TestCase
  
  def setup
    @common = Common.new
    @virtual_cable = DeviceConsole::NetConfig::VirtualCable.new
    @interface_zone = DeviceConsole::NetConfig::InterfaceZone.new

    assert_success do
      @common.set_current_device( $common["login_hash"] ) # 设置正确的当前设备的IP,用户名,密码
    end
  end
  
  def test_add_and_delete_virtual_cable
    #设置eth4为虚拟网线模式
    assert_hope("成功") do
      @interface_zone.edit_physical_interface( { :name => "eth4", :enable => "是", :description => "描述描述", :type => "虚拟网线",
          :is_wan => "否", :enable_ping => "是", :link_type => "静态IP", :static_ip => "192.168.0.60",
          :gateway => "", :dhcp_add_default_route => "否", :adsl_account => "", :adsl_passwd => "",
          :adsl_shake_time => "20", :adsl_timeout => "80", :adsl_retry_times => '3', :adsl_auto => "是",
          :adsl_add_default_route => "否", :adsl_first_dns => "否", :up_bandwidth => "10MB/s", :down_bandwidth => "10MB/s",
          :enable_link_trouble_check => "否", :check_method => "PING", :ping_ip => "202.96.137.23", :dns_server => "2.2.2.2",
          :dns_domain => "www.sangfor.com", :check_interval => "2", :access_id => "1", :native_id => "1", :vlan_scope => "1-1000",
          :work_mode => "自动协商", :mtu => 1500, :mac => "" } )
    end
    #设置eth5为虚拟网线模式
    assert_hope("成功") do
      @interface_zone.edit_physical_interface( { :name => "eth5", :enable => "是", :description => "描述描述", :type => "虚拟网线",
          :is_wan => "否", :enable_ping => "是", :link_type => "静态IP", :static_ip => "192.168.0.61",
          :gateway => "", :dhcp_add_default_route => "否", :adsl_account => "", :adsl_passwd => "",
          :adsl_shake_time => "20", :adsl_timeout => "80", :adsl_retry_times => '3', :adsl_auto => "是",
          :adsl_add_default_route => "否", :adsl_first_dns => "否", :up_bandwidth => "10MB/s", :down_bandwidth => "10MB/s",
          :enable_link_trouble_check => "否", :check_method => "PING", :ping_ip => "202.96.137.23", :dns_server => "2.2.2.2",
          :dns_domain => "www.sangfor.com", :check_interval => "2", :access_id => "1", :native_id => "1", :vlan_scope => "1-1000",
          :work_mode => "自动协商", :mtu => 1500, :mac => "" } )
    end
    #新建eth4和eth5为虚拟网线通道
    assert_hope("成功") do
      @virtual_cable.add_virtual_cable({:name => "4_5", :description => "5_4",
          :interface1 => "eth4", :interface2 => "eth5" })
    end
    #部分删除虚拟网线通道
    assert_hope("成功") do
      @virtual_cable.delete_virtual_cable({:delete_type => "部分删除", :names =>"4_5"})
    end
    #新建eth4和eth5为虚拟网线通道
    assert_hope("成功") do
      @virtual_cable.add_virtual_cable({:name => "4_5", :description => "5_4",
          :interface1 => "eth4", :interface2 => "eth5" })
    end
    #删除所有的虚拟网线
    assert_hope("成功") do
      @virtual_cable.delete_virtual_cable({:delete_type => "全部删除", :names => ""})
    end
    #还原eth4为路由模式
    assert_hope("成功") do
      @interface_zone.edit_physical_interface( { :name => "eth4", :enable => "是", :description => "描述描述", :type => "路由",
          :is_wan => "否", :enable_ping => "是", :link_type => "静态IP", :static_ip => "192.168.0.60",
          :gateway => "", :dhcp_add_default_route => "否", :adsl_account => "", :adsl_passwd => "",
          :adsl_shake_time => "20", :adsl_timeout => "80", :adsl_retry_times => '3', :adsl_auto => "是",
          :adsl_add_default_route => "否", :adsl_first_dns => "否", :up_bandwidth => "10MB/s", :down_bandwidth => "10MB/s",
          :enable_link_trouble_check => "否", :check_method => "PING", :ping_ip => "202.96.137.23", :dns_server => "2.2.2.2",
          :dns_domain => "www.sangfor.com", :check_interval => "2", :access_id => "1", :native_id => "1", :vlan_scope => "1-1000",
          :work_mode => "自动协商", :mtu => 1500, :mac => "" } )
    end
    #还原eth4为路由模式
    assert_hope("成功") do
      @interface_zone.edit_physical_interface( { :name => "eth5", :enable => "是", :description => "描述描述", :type => "路由",
          :is_wan => "否", :enable_ping => "是", :link_type => "静态IP", :static_ip => "192.168.0.61",
          :gateway => "", :dhcp_add_default_route => "否", :adsl_account => "", :adsl_passwd => "",
          :adsl_shake_time => "20", :adsl_timeout => "80", :adsl_retry_times => '3', :adsl_auto => "是",
          :adsl_add_default_route => "否", :adsl_first_dns => "否", :up_bandwidth => "10MB/s", :down_bandwidth => "10MB/s",
          :enable_link_trouble_check => "否", :check_method => "PING", :ping_ip => "202.96.137.23", :dns_server => "2.2.2.2",
          :dns_domain => "www.sangfor.com", :check_interval => "2", :access_id => "1", :native_id => "1", :vlan_scope => "1-1000",
          :work_mode => "自动协商", :mtu => 1500, :mac => "" } )
    end
  end
end