# coding: utf-8
#
# This file is generated by att util tool.
# by 2012-12-29 09:19:53
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../../') unless $LOADED
require 'keywords/unittests/setup'

class TestAutoitxStartServer < Test::Unit::TestCase
  def setup
    #you can use $local_pc_network_server_autoitx_start_server to quote hash as argument.
    @o = keyword_proxy_for_class_name( LocalPc::NetworkServer::AutoitxStartServer ).new
  end
  
  def test_start_tcp_server
    test_del_hash = []
    test_del_hash << {:port => "8886"} 
    test_del_hash.each { |test_hash|
      assert_success do
        @o.start_tcp_server(test_hash)
      end
    }
  end

  def test_stop_tcp_server
    test_del_hash = []
    test_del_hash << {:port => "8886"}
    test_del_hash.each { |test_hash|
      assert_success do
        @o.stop_tcp_server(test_hash)
      end
    }
  end
  
end