# coding: utf8
#
# This file is generated by att util tool.
# by 2012-05-18 14:51:12
#
$LOAD_PATH.unshift File.join(File.dirname(__FILE__),'../../../') unless $LOADED
require 'keywords/unittests/setup'

$stdouttype = "utf-8"

class TestDataBaseOperation < Test::Unit::TestCase
  def setup
    @db_operation = keyword_proxy_for_class_name( DeviceBack::DataBaseOperation ).new
  end
=begin
  def test_query_ips_log
    # 有查询结果,期望有日志,但期望记录是空
    assert_success do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "" })
    end
    # 有查询结果,期望有日志,期望记录比实际记录多,与实际不一致
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-#-&web#TCP#-#2.2.2.2#-#-#3.3.3.3#-#-#-#-#-#-" })
    end
    # 有查询结果,期望有日志,期望记录比实际记录多,但与实际一致
    assert_success do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-#-&web#TCP#lan#200.200.84.254#2292#wan#100.0.0.9#8888#10000#-#11#高#允许" })
    end
#=begin
    # 有查询结果,期望有日志,期望记录与实际一致,仅检查部分字段
    assert_success do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-#-" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致,检查所有字段
    assert_success do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#lan#200.200.84.254#2292#wan#100.0.0.9#8888#10000#-#11#高#允许" })
    end   
    # 有查询结果,期望有日志,期望记录与实际不一致
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#2.2.2.2#-#-#3.3.3.3#-#-#-#-#-#-" })
    end

    # 有查询结果,期望有日志,期望记录的字段数多了
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-#-#-" })
    end
    # 有查询结果,期望有日志,期望记录的字段数少了
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-" })
    end

    # 有查询结果,期望有日志,期望记录中的漏洞类型名称不存在于数据库中
    assert_hope("参数错误") do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "AAA#TCP#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-#-" })
    end
    # 有查询结果,期望有日志,期望记录中的协议不存在于数据库中
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#AAA#-#200.200.84.254#-#-#100.0.0.9#-#-#-#-#-#-" })
    end

    # 有查询结果,期望有日志,期望记录中的漏洞ID不存在于数据库中
    assert_success do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#10000#AAA#-#-#-" })
    end
    # 有查询结果,期望有日志,期望记录中的严重等级不存在于数据库中
    assert_hope("参数错误") do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#10000#-#-#高高#-" })
    end
    # 有查询结果,期望有日志,期望记录中的动作不存在于数据库中
    assert_hope("参数错误") do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "00:00:00",
        :enddate => "2012-05-11", :endtime => "23:59:59", :log_exist => "有" ,:records_hoped => "web#TCP#-#200.200.84.254#-#-#100.0.0.9#-#10000#-#-#-#动作" })
    end

    # 有查询结果,期望无日志
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-11", :starttime => "02:00:00",
        :enddate => "2012-05-11", :endtime => "13:59:59", :log_exist => "无" , :records_hoped => "web#TCP#-#2.2.2.2#-#-#3.3.3.3#-#-#-#-#-#-" })
    end
    # 无查询结果,期望无日志
    assert_success do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-16", :starttime => "02:00:00",
        :enddate => "2012-05-20", :endtime => "13:59:59", :log_exist => "无" , :records_hoped => "web#TCP#-#2.2.2.2#-#-#3.3.3.3#-#-#-#-#-#-" })
    end
    # 无查询结果,期望有日志
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2012-05-16", :starttime => "02:00:00",
        :enddate => "2012-05-20", :endtime => "13:59:59", :log_exist => "有" , :records_hoped => "web#TCP#-#2.2.2.2#-#-#3.3.3.3#-#-#-#-#-#-" })
    end
    # 20090512表不存在
    assert_fail do
      @db_operation.query_ips_log({:devicename => $common['device_name'], :startdate => "2009-05-11", :starttime => "02:00:00",
        :enddate => "2009-05-12", :endtime => "13:59:59", :log_exist => "无" ,:records_hoped => "web#TCP#-#2.2.2.2#-#-#3.3.3.3#-#-#-#-#-#-" })
    end
#=end
  end

  def test_query_dos_defence_log # 攻击类型#源区域#源IP#目的IP#匹配策略名#描述#严重等级#动作
    # 有查询结果,期望有日志,期望记录与实际一致,仅检查部分字段
    assert_success do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "内网DOS攻击#LAN1#192.168.22.9#192.168.22.1#-#-#高#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致,检查所有字段
    assert_success do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "IP地址扫描#wan#192.168.22.9#180.180.180.9#aaa#每源IP，200包/秒#中#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致,仅检查部分字段
    assert_success do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "黑名单中的IP报文#wan#192.168.22.9#180.180.180.9#aaa#-#中#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致,检查三条记录
    assert_success do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "黑名单中的IP报文#wan#192.168.22.9#180.180.180.9#aaa#-#中#拒绝&IP地址扫描#wan#192.168.22.9#180.180.180.9#aaa#每源IP，200包/秒#中#拒绝&内网DOS攻击#LAN1#192.168.22.9#192.168.22.1#-#-#高#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际不一致,仅检查部分字段
    assert_fail do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "内网DOS攻击#LAN1#192.168.22.9#192.168.22.1#-#-#高#允许" })
    end
    # 有查询结果,期望有日志,期望记录与实际不一致,检查所有字段
    assert_fail do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "IP地址扫描#wan#192.168.22.9#180.180.180.9#aaa#每源IP，300包/秒#中#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际不一致,仅检查部分字段
    assert_fail do
      @db_operation.query_dos_defence_log({:devicename => $common['device_name'], :startdate => "2012-05-22", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "黑名单中的IP报文#wan#192.168.22.9#180.180.180.9#bbb#-#中#允许" })
    end
  end
=end  
  def test_query_waf_defence_log # 攻击类型#源区域#源IP#目的IP#匹配策略名#严重等级#动作
    # 有查询结果,期望有日志,期望记录与实际一致,仅检查部分字段
    assert_success do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "11:40:40",
        :enddate => "2012-08-29", :endtime => "11:50:40", :log_exist => "有" , :records_hoped => "暴力破解FTP口令#lan#5.5.88.5#5.5.89.6#-#高#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致,检查所有字段
    assert_success do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "11:40:40",
         :enddate => "2012-08-29", :endtime => "11:50:40", :log_exist => "有" , :records_hoped => "暴力破解FTP口令#lan#5.5.88.5#5.5.89.6#woolen#高#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致,仅检查部分字段
    assert_success do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "11:40:40",
        :enddate => "2012-08-29", :endtime => "11:54:57", :log_exist => "有" , :records_hoped => "敏感信息防护#-#-#5.5.89.6#woolen#-#-" })
    end
    # 有查询结果,期望有日志,期望记录与实际一致
    assert_success do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "11:52:40",
        :enddate => "2012-08-29", :endtime => "11:54:40", :log_exist => "有" , :records_hoped => "弱口令类型-长度小于等于6位仅数字和字母#-#-#5.5.89.6#woolen#-#-" })
    end
    # 有查询结果,期望有日志,期望记录与实际不一致,仅检查部分字段
    assert_fail do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "06:19:22",
        :enddate => "2012-08-29", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "敏感信息防护#-#-#-#-#高#允许" })
    end
    # 有查询结果,期望有日志,期望记录与实际不一致,时间错位
    assert_fail do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "06:19:22",
        :enddate => "2012-05-22", :endtime => "07:33:48", :log_exist => "有" , :records_hoped => "敏感信息防护#-#-#-#-#中#拒绝" })
    end
    # 有查询结果,期望有日志,期望记录与实际不一致,仅检查部分字段
    assert_fail do
      @db_operation.query_waf_defence_log({:devicename => $common['device_name'], :startdate => "2012-08-29", :starttime => "06:19:22",
        :enddate => "2012-08-29", :endtime => "13:33:48", :log_exist => "有" , :records_hoped => "暴力破解FTP口令#-#-#-#-#-#abc#-" })
    end
  end
  
end